language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: SrhDn81I5omWfwWuwoJcegXr7yKHBmwXx+mPRGYSG2h3EEfakOiFCUdO/EHHbSsfrnSBSJQG0GSxw3oSt5ujZ3Um7J/tSsxVUWDc7i2/zmKpwu4zPHubhpD+T6JUbMX1NaVK6CjPYHPq1hEUlljYmI1gWc6EmdMbXlGF3S87Y442bAsqN7jyG6KU0wT8yIQfLJ3gx9qiifwzc0BuZbIeZY28FtG77OyVg17zhLfta4SZbkZSsZKr8Qd9MVKxvQqdJGoAC4BbSYmU2Y4SB8E6C6AUYkpysJAkoqwboh0EPvrRPr5YE3BtrnaWfqrCI9seKvHgx3JWqPPLPi1fvgi8vjlja6zBdLU1P8YU3ek+7fV3ejoahhOjqnqldjI+62HAau6w1TC3xfRNWb5eeTqYx9JWzhDlhLkpel7AZmn+rul+szxSpPN+4usna3Es437wUXmekUMgC4iD6xQSUsLTGRUwxYUk90ugmMSRqs1XfzMaVoZVUei/UKlNsUouBc2La03c+Xt2YyKREKZrSGJfpmuzYzhKz9ayFmmUODpT84ncRtVQfe7Vyvm8WcKhufHUgkIl8mXi7JjeE754+olXpcNqEPXn88A+icm9y5sJHFcC8d9T/wveR09ZUtLbB73wr5ZOJq67gG6wmu51ypn/oN/Mn9ZrQ5zBETmeLB+P61o=
  app: devopspipeline
  edge: true
