language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ApFIFaDZMkvKurRWkOxuRTClW6DwoHmhHX9ROX+wwwFdfufB3jgmeJjbnhOqn7bVRpaHNTeJPcyTynpg52H8C3F4r0Na78sTNanpmMXhBNdRDeISCD6rWcEECxVDuULQW52zPiuHBHs3wO1iN2Pds8WLKhC/J86+/OvlCABn1G/7vz5luQAFf0Kq/2+32ZsPkXZEeClOOPzKun1cMh8mKaekBc0I79lHppl7eWvUNTxvL9cH3LAVHkTnSA9cOiIy2asETezIQtGbuQVLXMO2ZRF9BhfFSj+3LELZxGAbq2NTXlIET2Mzc6M/OjBEikngqwfqX+GivPrEkElAop+QlqBW/wIRZVZOnip13f11k7MhW4gPn9TE9VFKB+Txj861b5tAl/xnQaHCdtKO2+DiS9c1WkfIjtZia3QMCjjYaCvJoE2tpVBd1W65p0AJkHZSGaKoNCnZaQ3mkdaFDpqi2R82jdWhuWKRMzgiwxFWmvIvkdA8LDLWTwqiM7ZdDNcPTEBMbSDjidcGNi4DVMbC08npmjQJ34CyjRhtfMBVo/BqOV07ftlGEflq+YhZ+9p1XZ1h4OqZnXdcpQopcxZqsvtl60KG7hWe+Ya6E1WkXB9viiyHc7qWWPMqmtShtIAgy6VBrACaR7+O9tzD5cxdAIRIwyBuYFAfSRiqgSR+yBk=
  app: devopspipeline
  edge: true
